tier1_integration:
  enabled: true
  tools:
    spec_builder:
      enabled: true
      quick_mode_available: true
      template_dir: templates/specs
      default_template: feature
    tdd_enforcer:
      enabled: true
      quick_mode_available: true
      coverage_threshold: 85.0
      strict_mode: false
    tag_tracer:
      enabled: true
      chain_validation: true
      auto_tag_suggestion: true
  mitigation:
    tutorial:
      enabled: true
      show_on_first_use: true
      tutorial_dir: docs/tutorials
    usage_tracking:
      enabled: true
      track_time_saved: true
      cumulative_display: true
      evidence_dir: RUNS/evidence
    quick_mode:
      enabled: true
      bypass_spec_creation: false
      warning_only: true
    weekly_report:
      enabled: true
      schedule: friday
      email_enabled: false
      console_output: true
  emergency:
    disable_all_tier1: false
    rollback_to_baseline: false
    last_emergency_datetime: '2025-10-25T02:35:16.291717'
