name: Quality Gate

on:
  pull_request:
    branches: [main, master]
    paths:
      - 'scripts/**'
      - 'tests/**'
      - '**.py'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov ruff

      - name: Run Ruff linting
        run: |
          ruff check scripts/ tests/

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=scripts --cov-report=json --cov-report=term

      - name: Check test coverage
        run: |
          coverage=$(python -c "import json; data=json.load(open('coverage.json')); print(data['totals']['percent_covered'])")
          echo "Test coverage: ${coverage}%"
          if (( $(echo "$coverage < 90.0" | bc -l) )); then
            echo "❌ Quality Gate FAILED: Coverage ${coverage}% < 90.0%"
            exit 1
          fi
          echo "✅ Quality Gate PASSED: Coverage ${coverage}% >= 90.0%"

      - name: Run DeepAnalyzer (if exists)
        continue-on-error: true
        run: |
          if [ -f scripts/deep_analyzer.py ]; then
            python scripts/deep_analyzer.py scripts/ tests/
          fi

      - name: Check Quality Score (if TeamStatsAggregator exists)
        continue-on-error: true
        run: |
          if [ -f scripts/team_stats_aggregator.py ]; then
            python scripts/team_stats_aggregator.py
            if [ -f RUNS/stats/team_stats.json ]; then
              score=$(python -c "import json; data=json.load(open('RUNS/stats/team_stats.json')); print(data.get('avg_quality_score', 10.0))")
              echo "Quality score: ${score}/10.0"
              if (( $(echo "$score < 7.0" | bc -l) )); then
                echo "⚠️ Quality score below threshold: ${score} < 7.0"
              fi
            fi
          fi

      - name: Quality Gate Summary
        if: success()
        run: |
          echo "✅ All quality checks passed!"
          echo "- Ruff linting: PASS"
          echo "- Test coverage: PASS (>= 90%)"
          echo "- Code quality: PASS"
